using Ambev.DeveloperEvaluation.Common.Security;
using Ambev.DeveloperEvaluation.Common.Validation;
using Ambev.DeveloperEvaluation.Domain.Common;
using Ambev.DeveloperEvaluation.Domain.Enums;
using Ambev.DeveloperEvaluation.Domain.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ambev.DeveloperEvaluation.Domain.Entities;


/// <summary>
/// Represents a client in the system.
/// </summary>
public class Client
{
    /// <summary>
    /// Gets the client's id.
    /// Its generated by the database during its creation.
    /// </summary>
    [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }
    /// <summary>
    /// Gets the clint's name.
    /// Must not be null or empty.
    /// </summary>
    [Required]
    [StringLength(250)]
    public string Name { get; set; } = string.Empty;
    /// <summary>
    /// Gets the date and time when the client was created.
    /// </summary>
    public DateTime CreatedAt { get; set; }
    public Client()
    {
        CreatedAt = DateTime.UtcNow;
    }
}