using Ambev.DeveloperEvaluation.Common.Security;
using Ambev.DeveloperEvaluation.Common.Validation;
using Ambev.DeveloperEvaluation.Domain.Common;
using Ambev.DeveloperEvaluation.Domain.Enums;
using Ambev.DeveloperEvaluation.Domain.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ambev.DeveloperEvaluation.Domain.Entities;


/// <summary>
/// Represents a user in the system with authentication and profile information.
/// This entity follows domain-driven design principles and includes business rules validation.
/// </summary>
public class Product
{
    /// <summary>
    /// Gets the product's id.
    /// Its generated by the database during its creation.
    /// </summary>
    [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }
    /// <summary>
    /// Gets the product's name.
    /// Must not be null or empty.
    /// </summary>
    [Required]
    [StringLength(250)]
    public string Name { get; set; } = string.Empty;
    /// <summary>
    /// Gets the product's description.
    /// Must not be null or empty.
    /// </summary>
    [Required]
    [StringLength(250)]
    public string Description { get; set; } = string.Empty;
    /// <summary>
    /// Gets the product's price.
    /// Must be a decimal.
    /// </summary>
    [Required]
    public decimal Price { get; set; }
    /// <summary>
    /// Gets the list of entitys sales item of the cureent product.
    /// </summary>
    [Required]
    public List<SalesProduct> SalesProduct { get; set; }
    /// <summary>
    /// Gets the date and time when the product was created.
    /// </summary>
    public DateTime CreatedAt { get; set; }
    public Product()
    {
        CreatedAt = DateTime.UtcNow;
    }
}